//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnowDocumentDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnowDocumentDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Content FROM SnowLicenseManager.dbo.tblDocuments
        ///WHERE  CID = @CID AND DocumentID = @FileID.
        /// </summary>
        internal static string GetDocumentContent {
            get {
                return ResourceManager.GetString("GetDocumentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	C.ContractID,
        ///	C.Name AS [Agreement Name],
        ///	C.AssignedID AS [Agreement Number],
        ///	D.DocumentID AS [File ID],
        ///	D.Description AS [File Info],
        ///	D.FileName,
        ///	D.Extension,
        ///	D.ContentType
        ///FROM SnowLicenseManager.dbo.tblDocuments D
        ///INNER JOIN SnowLicenseManager.dbo.tblContract C ON D.ParentID = C.ContractID
        ///WHERE DocumentType = 2 AND C.CID = @CID.
        /// </summary>
        internal static string GetDocumentDataAgreements {
            get {
                return ResourceManager.GetString("GetDocumentDataAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	C.ComputerID,
        ///	C.HostName, 
        ///	C.BiosSerialNumber,
        ///	D.DocumentID AS [File ID],
        ///	D.Description AS [File Info],
        ///	D.FileName,
        ///	D.Extension,
        ///	D.ContentType
        ///FROM SnowLicenseManager.dbo.tblDocuments D
        ///INNER JOIN SnowLicenseManager.dbo.tblComputer C on D.ParentID = C.ComputerID
        ///WHERE DocumentType = 3 AND C.CID = @CID.
        /// </summary>
        internal static string GetDocumentDataComputers {
            get {
                return ResourceManager.GetString("GetDocumentDataComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	L.LicenseID,
        ///	A.Name,
        ///	L.InvoiceReference,
        ///	CONVERT(NVARCHAR, L.PurchaseDate) AS [Purchase Date],
        ///	L.LegalLicenseCount,
        ///	D.DocumentID AS [File ID],
        ///	D.Description AS [File Info],
        ///	D.FileName,
        ///	D.Extension,
        ///	D.ContentType
        ///FROM SnowLicenseManager.dbo.tblDocuments D
        ///INNER JOIN SnowLicenseManager.dbo.tblLicense L ON D.ParentID = L.LicenseID
        ///INNER JOIN SnowLicenseManager.dbo.tblApplication A ON L.ApplicationID = A.ApplicationID
        ///WHERE DocumentType = 1 AND L.CID = @CID.
        /// </summary>
        internal static string GetDocumentDataLicenses {
            get {
                return ResourceManager.GetString("GetDocumentDataLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	U.UserID, 
        ///	U.UserName,
        ///	D.DocumentID AS [File ID],
        ///	D.Description AS [File Info],
        ///	D.FileName,
        ///	D.Extension,
        ///	D.ContentType
        ///FROM SnowLicenseManager.dbo.tblDocuments D
        ///INNER JOIN SnowLicenseManager.dbo.tblUser U ON D.ParentID = U.UserID
        ///WHERE DocumentType = 4  AND U.CID = @CID.
        /// </summary>
        internal static string GetDocumentDataUsers {
            get {
                return ResourceManager.GetString("GetDocumentDataUsers", resourceCulture);
            }
        }
    }
}
